blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls')),
    path('account/', include('users.urls')),
]

blog/users/urls.py
from django.urls import path
from users import views

app_name = "users"

urlpatterns = [
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('register/', views.UserRegisterView.as_view(), name='register'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),
    path('profile/', views.UserProfileView.as_view(), name='profile'),
]

blog/website/urls.py
from django.urls import path
from website import views

app_name = "website"

urlpatterns = [
    path('', views.AllItemsView.as_view(), name='index'),
    path('delete/<int:pk>/', views.DeletePostView.as_view(), name='delete'),
    path('update/<int:pk>/', views.UpdatePostView.as_view(), name='update'),
    path('create/', views.CreatePostView.as_view(), name='create'),
    path('myposts/', views.MyPostsView.as_view(), name='myposts'),
    path('post/<int:pk>', views.BlogPostDetailView.as_view(), name='detail'),
]

blog/users/models.py
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models

class CustomUserManager(BaseUserManager):
    def create_user(self, email, username, password=None, **extra_fields):
        if not email:
            raise ValueError("The Email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        return self.create_user(email, username, password, **extra_fields)

class CustomUser(AbstractBaseUser, PermissionsMixin):
    GENDERS = [
        ("Male", "Male"),
        ("Female", "Female"),
        ("Prefer not to say", "Prefer not to say"),
    ]

    email = models.EmailField(unique=True)
    full_name = models.CharField(max_length=255)
    username = models.CharField(max_length=255, unique=True)
    phone = models.CharField(max_length=255)
    gender = models.CharField(choices=GENDERS, max_length=255)

    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)

    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.full_name

blog/users/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserChangeForm


User = get_user_model()

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['email', 'full_name', 'username', 'phone', 'gender', 'password1', 'password2']

class CustomUserProfileForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['full_name', 'username', 'email', 'phone', 'gender']

    def clean_gender(self):
        gender = self.cleaned_data.get('gender')
        if gender not in dict(User.GENDERS):
            raise forms.ValidationError("Invalid gender selection.")
        return gender
    
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if User.objects.exclude(id=self.instance.id).filter(username=username).exists():
            raise forms.ValidationError("Custom user with this Username already exists.")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if User.objects.exclude(id=self.instance.id).filter(email=email).exists():
            raise forms.ValidationError("An account with this email already exists.")
        return email

class CustomAuthenticationForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ['email', 'password']

    def clean_username(self):
        email = self.cleaned_data.get('email')
        try:
            user = User.objects.get(email=email)
            return user.username  # Return the username for authentication
        except User.DoesNotExist:
            raise forms.ValidationError("This email is not registered.")    

blog/users/views.py
from multiprocessing import context
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth import login
from django.contrib.auth import get_user_model
from django.views.generic import CreateView, UpdateView
from .forms import CustomUserCreationForm, CustomUserProfileForm
from django.contrib import messages
from django.urls import reverse_lazy
from users.mixins import RedirectAuthenticatedUserMixin
from django.contrib.auth.mixins import LoginRequiredMixin

User = get_user_model()


class UserLoginView(RedirectAuthenticatedUserMixin, LoginView):
    template_name = "users/login.html"

    def get_success_url(self):
        return reverse_lazy("website:index")

    def form_valid(self, form):
        messages.success(self.request, "Login successful.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Invalid login credentials. Please try again.")
        return self.render_to_response(self.get_context_data(form=form))


class UserRegisterView(RedirectAuthenticatedUserMixin, CreateView):
    models = User
    template_name = "users/register.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse_lazy("website:index")

    def form_valid(self, form):
        # form.save()                           # save the form
        user = form.save()  # save the form for user
        login(self.request, user)  # if you want login user without login again
        messages.success(self.request, "Registration successful. Please log in.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(
            self.request, "Invalid registrations credentials. Please try again."
        )
        return self.render_to_response({"form": form})


class UserLogoutView(LogoutView):
    def get_success_url(self):
        return reverse_lazy("users:login")

    def dispatch(self, request, *args, **kwargs):
        messages.success(request, "Successfully logged out.")
        return super().dispatch(request, *args, **kwargs)


class UserProfileView(LoginRequiredMixin, UpdateView):
    template_name = "users/profile.html"
    form_class = CustomUserProfileForm
    success_url = reverse_lazy("users:profile")

    def get_object(self, queryset=None):
        return self.request.user

    def form_valid(self, form):
        messages.success(self.request, "Profile updated successfully.")
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Error updating profile. Please try again.")
        return self.render_to_response(self.get_context_data(form=form))
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Profile"
        context["genders"] = User.GENDERS
        return context

blog/users/templates/users/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title> Registration | Login Form </title>
  <link rel="stylesheet" href="{% static "css/login_register.css" %} ">
  <link rel="stylesheet" href="{% static 'css/notifications.css' %}" />
  <script src="{% static 'js/notifications.js' %}"></script>
</head>
<body>
  {% include "includes/notifications.html" %}

  {% block content %}{% endblock content %}
</body>
</html>

blog/users/templates/users/login.html
{% extends "users/base.html" %}

{% block content %}
<div class="container">
    <!-- Title section -->
    <div class="title">Login</div>
    <div class="content">
      <!-- Login form -->
      <form method="POST" action="{% url 'users:login' %}">
        {% csrf_token %}

        <div class="user-details">
          <!-- Input for Email -->
          <div class="input-box">
            <span class="details">Email</span>
            <input type="text" name="username" placeholder="Enter your email" required>
            {% if form.username.errors %}
                <div class="error">
                    {% for error in form.username.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
          </div>
          <!-- Input for Password -->
          <div class="input-box">
            <span class="details">Password</span>
            <input type="password" name="password" placeholder="Enter your password" required>
            {% if form.password.errors %}
                <div class="error">
                    {% for error in form.password.errors %}
                        <span>{{ error }}</span>
                    {% endfor %}
                </div>
            {% endif %}
          </div>
        </div>
        <!-- Submit button -->
        <div class="button">
            <a href="{% url "users:register" %}">Don't have account?</a>
          <input type="submit" value="Login">
        </div>
      </form>
    </div>
  </div>
{% endblock content %}

blog/users/templates/users/profile.html
{% extends "website/base.html" %}

{% block content %}
<style>
    .container {
        display: flex;
        flex-direction: column; /* Stack elements vertically */
        max-width: 600px; /* Set a maximum width for the form */
        margin: 20px auto; /* Center the container */
        padding: 20px; /* Padding around the container */
        background-color: #fff; /* Background color */
        border-radius: 8px; /* Rounded corners */
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1); /* Shadow effect */
    }
</style>
<div class="container">
    <h2>PROFILE</h2>
    <form method="POST" action="{% url 'users:profile' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="title">Full name:</label>
            <input type="text" name="full_name" maxlength="100" value="{{ form.full_name.value }}" required>
        </div>
        <div class="form-group">
            <label for="title">Username:</label>
            <input type="text" name="username" maxlength="100" value="{{ form.username.value }}" required>
        </div>
        <div class="form-group">
            <label for="email">Email:</label>
            <input type="email" name="email" maxlength="100" value="{{ form.email.value }}" required>
        </div>
        
        <div class="form-group">
            <label for="title">Phone:</label>
            <input type="text" name="phone" maxlength="100" value="{{ form.phone.value }}" required>
        </div>
        <div class="form-group">
            <label for="gender">Gender:</label>
            <select name="gender" required>
                <option value="{{ form.gender.value }}">{{ form.gender.value }}</option>
                {% for value, display in genders %}
                    <option value="{{ value }}">{{ display }}</option>
                {% endfor %}
            </select>
        </div>
        <button type="submit" class="btn save-btn" onclick="confirmUpdateProfile(event)">Save</button>
        <a href="{% url 'website:myposts' %}" class="btn back-btn">Back</a>
    </form>
</div>
{% endblock content %}

blog/users/templates/users/register.html
{% extends "users/base.html" %}

{% block content %}

<div class="container">
    <!-- Title section -->
    <div class="title">Registration</div>
    <div class="content">
      <!-- Registration form -->
      <form method="POST" action="{% url 'users:register' %}">
        {% csrf_token %}

        <div class="user-details">
          <!-- Input for Full Name -->
          <div class="input-box">
            <span class="details">Full Name</span>
            <input type="text" name="full_name" placeholder="Enter your name" required>
            {% if form.full_name.errors %}
            <div class="error">
                {% for error in form.full_name.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
          </div>
          <!-- Input for Username -->
          <div class="input-box">
            <span class="details">Username</span>
            <input type="text" name="username" placeholder="Enter your username" required>
          </div>
          <!-- Input for Email -->
          <div class="input-box">
            <span class="details">Email</span>
            <input type="text" name="email" placeholder="Enter your email" required>
            {% if form.username.errors %}
            <div class="error">
                {% for error in form.username.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
          </div>
          <!-- Input for Phone Number -->
          <div class="input-box">
            <span class="details">Phone Number</span>
            <input type="text" name="phone" placeholder="Enter your number" required>
            {% if form.email.errors %}
            <div class="error">
                {% for error in form.email.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
          </div>
          <!-- Input for Password -->
          <div class="input-box">
            <span class="details">Password</span>
            <input type="password" name="password1" placeholder="Enter your password" required>
            {% if form.password1.errors %}
            <div class="error">
                {% for error in form.password1.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
          </div>
          <!-- Input for Confirm Password -->
          <div class="input-box">
            <span class="details">Confirm Password</span>
            <input type="password" name="password2" placeholder="Confirm your password" required>
            {% if form.password2.errors %}
            <div class="error">
                {% for error in form.password2.errors %}
                    <span>{{ error }}</span>
                {% endfor %}
            </div>
            {% endif %}
          </div>
        </div>
        <div class="gender-details">
          <!-- Radio buttons for gender selection -->
          <input type="radio" name="gender" id="dot-1" value="Male">
          <input type="radio" name="gender" id="dot-2" value="Female">
          <input type="radio" name="gender" id="dot-3" value="Prefer not to say">
          <span class="gender-title">Gender</span>
          <div class="category">
            <!-- Label for Male -->
            <label for="dot-1">
              <span class="dot one"></span>
              <span class="gender">Male</span>
            </label>
            <!-- Label for Female -->
            <label for="dot-2">
              <span class="dot two"></span>
              <span class="gender">Female</span>
            </label>
            <!-- Label for Prefer not to say -->
            <label for="dot-3">
              <span class="dot three"></span>
              <span class="gender">Prefer not to say</span>
            </label>
          </div>
        </div>
        <!-- Submit button -->
        <div class="button">
          <input type="submit" value="Register">
        </div>
      </form>
    </div>
  </div>
{% endblock content %}