todo/todo/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include("website.urls")),
    path('', include("users.urls")),
]

todo/users/urls.py
from django.urls import path
from users import views
from django.contrib.auth.views import LogoutView

app_name = "users"

urlpatterns = [
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.CustomLogoutView.as_view(), name='logout'),
]

todo/website/urls.py
from django.urls import path
from website import views

app_name = "website"

urlpatterns = [
    path('', views.ItemsView.as_view(), name="index"),
    path('delete/<int:pk>/', views.DeleteItem.as_view(), name="delete"),
    path('update/<int:pk>/', views.UpdateItem.as_view(), name="update"),
    path('update-status/<int:pk>/', views.UpdateStatus.as_view(), name="update-status"),
]

todo/website/models.py
from django.db import models
from django.db.models import CASCADE
from django.contrib.auth import get_user_model


User = get_user_model()

class ToDoItems(models.Model):
    user = models.ForeignKey(to=User, on_delete=CASCADE)
    description = models.CharField(max_length=100, blank=False, null=False)
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.description

todo/website/forms.py
from django import forms
from .models import ToDoItems

class ToDoItemForm(forms.ModelForm):
    class Meta:
        model = ToDoItems
        fields = ['description']

todo/website/views.py
import json
from typing import Any, Dict
from django.contrib import messages
from django.shortcuts import get_object_or_404
from django.views import View
from django.views.generic import UpdateView
from django.views.generic.edit import DeleteView
from django.views.generic.list import ListView
from website.models import ToDoItems
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.edit import FormMixin
from django.http import HttpResponseRedirect, JsonResponse
from website.forms import ToDoItemForm
from django.urls import reverse_lazy


class ItemsView(LoginRequiredMixin, ListView, FormMixin):
    template_name = "website/index.html"
    success_url = reverse_lazy('website:index')
    form_class = ToDoItemForm
    
    def get_queryset(self):
        return ToDoItems.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        # Ensure 'object_list' is defined for the ListView
        if not hasattr(self, 'object_list'):
            self.object_list = self.get_queryset()
        context = super().get_context_data(**kwargs)
        context["items"] = self.get_queryset()
        context['form'] = ToDoItemForm()
        return context
    
    def post(self, request, *args, **kwargs):
        # Get the form without validation
        form = self.get_form()
        # Save the item directly, assuming client validation
        item = form.save(commit=False)
        item.user = self.request.user
        item.save()
        return HttpResponseRedirect(self.success_url)


class DeleteItem(LoginRequiredMixin, DeleteView):
    model = ToDoItems
    success_url = reverse_lazy('website:index')

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.delete()
        return JsonResponse({'success': True})


class UpdateItem(LoginRequiredMixin, UpdateView):
    model = ToDoItems
    fields = ['description']

    def post(self, request, *args, **kwargs):
        if request.headers.get('x-requested-with') == 'XMLHttpRequest':   #save item with ajax
            self.object = self.get_object()
            form = self.get_form()
            if form.is_valid():
                form.save()
                return JsonResponse({'success': True})
            else:
                return JsonResponse({'success': False, 'errors': form.errors}, status=400)
        return JsonResponse({'error': 'Non-AJAX request received'}, status=400)
    

class UpdateStatus(LoginRequiredMixin, View):
    def post(self, request, *args, **kwargs):
        # Parse JSON data
        try:
            data = json.loads(request.body)
        except json.JSONDecodeError:
            return JsonResponse({'error': 'Invalid JSON data'}, status=400)
        
        # Check if the request is specifically for a status update
        item = get_object_or_404(ToDoItems, pk=kwargs['pk'], user=request.user)
        status = data.get('status')
        
        # Ensure status is provided
        if status is None:
            return JsonResponse({'error': 'Missing status field'}, status=400)

        # Update the item's status and save
        item.status = status
        item.save()

        return JsonResponse({'success': True, 'status': item.status})

todo/website/templates/website/base.html
{% load static %}


<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>To Do Application</title>
    <link rel="stylesheet" href="{% static "css/style.css" %}" />
    <link rel="stylesheet" href="{% static 'css/notifications.css' %}" />
    <script src="{% static 'js/notifications.js' %}"></script>
  </head>
  <body>
    <div>
      <nav class="top-nav">
        <ul>
          <li><a href="{% url "website:index" %}" class="styled-button active">To-Do</a></li>
          <li>
            <form action="{% url 'users:logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="styled-button" onclick="confirmLogout(event)">Logout</button>
            </form>
          </li>
        </ul>
      </nav>
    </div>
    {% include "includes/notifications.html" %}

    {% block content %}{% endblock content %}
  </body>
</html>

todo/website/templates/website/index.html
{% extends 'website/base.html' %}
{% load static %}

{% block content %}
  <div class="container">
    <div class="todo-header">
      <h2>ToDo List</h2>
      <img src="{% static 'img/to-do-list.png' %}" height="50px" />
    </div>
    <form id="todo-form" method="post" action="{% url 'website:index' %}">
      {% csrf_token %}

      <div class="todo-body">
        <input type="text" id="todoText" name="description" class="todo-input" placeholder="Add your items" />
        <div id="error-message" style="color: red; display: none;">Please enter a description.</div>
        <button class="buttons" type="submit" id="add-item" style="background: none; border: none;"><img src="{% static 'img/plus.png' %}" alt="+" /></button>
      </div>
    </form>

    <ul id="list-items" class="list-items"></ul>
    {% for item in items %}
    <li id="item-{{ item.id }}" class="list-item {% if item.status %}completed{% endif %}" style="display: flex; justify-content: space-between; align-items: center; padding: 5px;">
      <div style="display: flex; align-items: center;">
        <!-- Checkbox -->
        <input type="checkbox" class="completed-checkbox" {% if item.status %}checked{% endif %} onclick="toggleComplete({{ item.id }})">
        
        <!-- Description -->
        <div id="description-container-{{ item.id }}" style="margin-left: 10px;">
            <span id="description-text-{{ item.id }}">{{ item.description }}</span>
            <input type="text" id="description-input-{{ item.id }}" value="{{ item.description }}" class="edit-input" style="display:none;" />
        </div>
      </div>

      <div class="action-buttons" style="display: flex; gap: 10px;">
        <!-- Edit button (will be hidden when editing) -->
        <button href="#" class="buttons" id="edit-button-{{ item.id }}" style="{% if item.status %}display:none;{% endif %}" onclick="editItem({{ item.id }}); return false;">
          <img src="{% static 'img/pen.png' %}" style="width: 25px; height: auto; margin-top: 5px;" />
        </button>
        <!-- Save button (hidden initially) -->
        <button id="save-button-{{ item.id }}" class="save-button buttons" onclick="saveItem({{ item.id }}); return false;" style="display:none;"><img src="{% static 'img/confirm.png' %}" style="width: 25px; height: auto; margin-top: 5px;" /></button>

        <!-- Cancel button (hidden initially) -->
        <button href="#" id="back-button-{{ item.id }}" class="buttons" onclick="cancelEdit({{ item.id }}); return false;" style="display:none;"><img src="{% static 'img/cancel.png' %}" style="width: 25px; height: auto; margin-top: 5px;" /></button>

        <!-- Delete button -->
        <form id="delete-form-{{ item.id }}" method="post" action="{% url 'website:delete' item.id %}">
          {% csrf_token %}
          <button type="submit" class="buttons" style="background: none; border: none;" onclick="confirmDelete(event)" id="delete-button-{{ item.id }}"><img src="{% static 'img/garbage.png' %}" style="width: 27px; height: auto; margin-right: 5px; margin-top: 5px;" /></button>
        </form>
      </div>
    </li>
    {% endfor %}
  </div>
  <script>
    document.getElementById('todo-form').addEventListener('submit', function (event) {
      const descriptionInput = document.getElementById('todoText') // Changed to match the id in HTML
      const errorMessage = document.getElementById('error-message')
    
      // Check if the input field is empty
      if (descriptionInput.value.trim() === '') {
        // Prevent form submission
        event.preventDefault()
        // Show error message
        errorMessage.style.display = 'block'
      } else {
        // Hide error message if there is input
        errorMessage.style.display = 'none'
      }
    })
  </script>
  <script type="text/javascript" src="{% static 'js/script.js' %}"></script>
{% endblock %}